version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - ${SP_DB_PORT}:3306
    environment:
      MYSQL_DATABASE: wordpress-playground
      MYSQL_USER: ${SP_USERNAME}
      MYSQL_PASSWORD: ${SP_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: unless-stopped
    ports:
      - ${SP_WEB_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress-playground
      WORDPRESS_DB_USER: ${SP_USERNAME}
      WORDPRESS_DB_PASSWORD: ${SP_PASSWORD}
    volumes:
      - ./src:/var/www/html

volumes:
  # wordpress:
  db: